[options]

; -------------------------------------------------------
; Addons Path
; -------------------------------------------------------
addons_path =
    /home/masbintang/linkederp/base/odoo/addons,
    /home/masbintang/linkederp/base/enterprise,
    /home/masbintang/linkederp/omnisurge/Odoo
;data_dir = /home/masbintang/linkederp/omnisurge/data
; -------------------------------------------------------
; Server
; Server
; -------------------------------------------------------
admin_passwd = 123
http_port = 8069
longpolling_port = 8072
; -------------------------------------------------------
; Database
; -------------------------------------------------------
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
;db_name = False
db_maxconn = 64
dbfilter = ^vania.*$

; -------------------------------------------------------
; Performance
; -------------------------------------------------------
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

; -------------------------------------------------------
; Misc
; -------------------------------------------------------
without_demo = True
proxy_mode = False

